# ================================
# DEVELOPMENT ENVIRONMENT
# ================================

# server port
server.port=8080

# in memory database (H2)
spring.datasource.url=jdbc:h2:mem:websitemonitoringdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# enable h2 console for debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# scheduler configuration (faster for dev testing)
monitoring.scheduler.fixed-rate=15s

# http timeout configuration
monitoring.http.timeout.connect=3000
monitoring.http.timeout.read=5000

# logging
logging.level.root=INFO
logging.level.com.matheus.websitemonitoring=DEBUG

# actuator (healthcheck)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never