# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:websitemonitoringdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# MONITORING CONFIG
# ===============================
# 15000 ms = 15 segundos (intervalo de monitoramento)
# 60000 ms = 60 segundos (1 minuto)
monitoring.scheduler.fixed-rate=15000
monitoring.http.timeout.connect=3000
monitoring.http.timeout.read=5000

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.matheus.websitemonitoring=DEBUG

